# Generated by Django 4.0 on 2021-12-26 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('num_rooms', models.IntegerField()),
                ('address', models.CharField(max_length=255)),
                ('star_rating', models.IntegerField()),
                ('phone_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra_bed', models.BooleanField(default=False)),
                ('room_type', models.CharField(choices=[('D', 'double'), ('T', 'twin'), ('S', 'single'), ('Tri', 'triple'), ('q', 'quad')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('occupancy', models.BooleanField(default=False)),
                ('hotel_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room.hotel')),
                ('room_type', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='room.roomtype')),
            ],
        ),
    ]
