# Generated by Django 4.0 on 2021-12-26 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='code',
            field=models.IntegerField(default=21),
            preserve_default=False,
        ),
    ]
