# Generated by Django 3.2 on 2021-12-30 07:13

from django.db import migrations
import user.models.utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_guest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='phone_number',
            field=user.models.utils.fields.PhoneNumberField(max_length=32),
        ),
    ]
