# Generated by Django 4.0 on 2021-12-27 21:18

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_hotel_code'),
        ('user', '0001_initial'),
        ('booking', '0002_booking_guest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='check_out',
        ),
        migrations.AddField(
            model_name='booking',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 12, 27, 21, 18, 46, 212795, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='guest',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.user'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='hotel',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='room.hotel'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='room',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='room.room'),
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='booking.booking')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.user')),
            ],
        ),
    ]
