# Generated by Django 4.0 on 2021-12-28 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_hotel_code'),
        ('booking', '0004_alter_booking_guest_alter_booking_hotel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='room.room'),
        ),
    ]
